name: RandomTeleporter
version: 1.0.0
author: KewaiiGamer
main: info.kewaiigamer.randomteleporter.Main
commands:
  tpran:
    description: Teleports to a random location
    usage: /tpran
permissions:
  randomteleport:
    description: Player can teleport